### ISSUE TITLE
萌新报道～

### ISSUE THREAD

**Issue by Eurus-Holmes** [bljx/BFU-sprig#4]
偶然发现计协在收集blog那也来凑个热闹好啦:see_no_evil:
[Feiyang Chen's Blog](http://blog.leanote.com/chenfeiyang)
  顺便歪个楼，想问下@MU001999 聚聚有没有广告位出租:see_no_evil:
有广告位的话我租一个:hear_no_evil:

> 欢迎对ML/DL/RL/NLP/CV/Audio research感兴趣的朋友与我联系，具体项目事宜详谈~
联系方式见我blog中的About Me~
非诚勿扰～

没有广告位的话就麻烦聚聚帮忙把广告第一句话作为我那里的备注吧:see_no_evil:

**Comment by ghost** [comment]
sdl...
等一个mu001999聚聚

**Comment by mu001999** [comment]
嘻嘻，有友情链接（底栏那儿
